version: "3"
services:
  node-api:
    image: forgione67/supplement-api
    build:
      context: ./nodeServer
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-api
