version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-api:
    image: forgione67/supplement-api
    build:
      context: ./nodeServer
    depends_on:
      - mongo

  mongo:
    image: forgione67/supplement-api-mongo
    build:
      context: ./
      dockerfile: Dockerfile.mongo

    container_name: mongo
    restart: always
    volumes:
      - ./mongodbData:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
