version: "3"
services:
  node-api:
    image: forgione67/supplement-api
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: npm start

  mongo:
    image: forgione67/supplement-api-mongo
    env_file:
      - ./.env

  nginx:
    ports:
      - "80:80"
