version: "3"
services:
  nginx:
    ports:
      - "3000:80"

  node-api:
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./nodeServer/:/usr/src/app:ro
      - /usr/src/app/node_modules
      - ./nodeServer/public/:/usr/src/app/public
    command: npm run dev

  mongo:
    image: forgione67/supplement-api-mongo
    build:
      context: ./
      dockerfile: Dockerfile.mongo
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - ./mongodbData:/data/db
    container_name: mongo
    restart: always
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME={MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD={MONGO_INITDB_ROOT_PASSWORD}

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    restart: on-failure
