pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {        

    stage('Install dependencies') {
      steps {
        dir('nodeServer/'){
            sh 'npm install'
        }
      }
    }
     
    stage('Test') {
      steps {
         echo 'Testing..' 
         sh 'npm test'
      }
    }      
  }
}